services:
  - type: web
    name: producteurs-locaux
    env: node
    buildCommand: npm install && cd client && npm install --include=dev && npm run build
    startCommand: node server/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000

